name: dot_dice_lite
description: Lite version of Dot Dice, a dice rolling app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Redaction20
      fonts:
        - asset: assets/fonts/redaction/OTF/Redaction20-Bold.otf
        - asset: assets/fonts/redaction/OTF/Redaction20-Italic.otf
        - asset: assets/fonts/redaction/OTF/Redaction20-Regular.otf